name: project4
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - numpy
  - matplotlib
  - pandas
  - scipy
  - opencv
  - pytorch==1.3.0
  - torchvision==0.4.1
  - pip
  - pip:
    - airsimneurips
    - pyglet==1.3.2
    - cloudpickle==1.2.0
